version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: healthcare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./HealthcareManagement-Backend
    container_name: healthcare-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    build: .
    container_name: healthcare-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
